---
# tasks file for khnixxo.os_users_groups

- name: include Group related task
  include: group.yml
  with_items: "{{ khnixxo_os_groups_selection | default([]) }}"
  loop_control:
    loop_var: selection_item

- name: include User Account related task
  include: user.yml
  with_items: "{{ khnixxo_os_users_selection | default([]) }}"
  loop_control:
    loop_var: selection_item